models:
  default:
    api_key: ""
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    model: "qwen3-max"
    temperature: 0.0
  qwen3-max-1:
    api_key: ""
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    model: "qwen3-max"
    temperature: 0.6
  qwen3-max-2:
    api_key: ""
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    model: "qwen3-max"
    temperature: 1.0
  qwen3-max-3:
    api_key: ""
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    model: "qwen3-max"
    temperature: 0.3
